# Generated by Django 3.1.6 on 2021-04-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('clock', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.user')),
            ],
        ),
    ]
