# Generated by Django 3.1.6 on 2021-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('time', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
