# Generated by Django 3.1.6 on 2021-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
