# Generated by Django 3.1.6 on 2021-04-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20210429_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fulladdress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='time',
            new_name='clock',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='contactnumber',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='fullname',
            new_name='name',
        ),
    ]
